### ISSUE TITLE
Email - STARTTLS

### ISSUE THREAD

**Issue by mitar** [meteor/meteor-feature-requests#10]
Migrated from: meteor/meteor#8637

**Comment by abernix** [comment]
@mitar Are you actually experiencing a problem with `STARTTLS` not working?

**Comment by mitar** [comment]
No, I just migrated it because I would like that it works if I will need it at some point. I have not tested it or confirmed it myself.

**Comment by abernix** [comment]
Ok, `STARTTLS` absolutely already works.
