### ISSUE TITLE
Allow configuring which user fields are published automatically

### ISSUE THREAD

**Issue by mitar** [meteor/meteor-feature-requests#12]
Migrated from: meteor/meteor#7743

**Comment by zimme** [comment]
I believe this could be in the same PR as #71.

**Comment by StorytellerCZ** [comment]
@filipenevola I believe this has already been done.

**Comment by crapthings** [comment]
https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L755


```js
Accounts.addAutopublishFields({
  forLoggedInUser: ['createdAt', 'secret'],
  forOtherUsers: ['createdAt'],
})
```

**Comment by mitar** [comment]
No, you can only ADD to published files, but not removed, [these fields are published always](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L37-L39).

**Comment by mitar** [comment]
I think what has been discussed in the original issue makes the most sense: moving this auto-publishing logic to a separate package which for backwards compatibility keeps the behavior and developers can then just remove the package.
