### ISSUE TITLE
DDP rate limiter, aggregate frequent calls

### ISSUE THREAD

**Issue by janat08** [meteor/meteor-feature-requests#138]
- Binding reactive form values- DOM- directly to model that triggers method calls would be cool.
- Call method on client, finally sending client oplog once ddpratelimiter allows, you could even send the object to client for it to not spam server, and run method again implementing oplog instead.
- I think that event binding is boring, and instead binding method directly to method with schema inffering what the value stands for would be fine thing indeed.

PS is think 3rd point should swap with 2nd as far as feature request protocol goes.

**Comment by mitar** [comment]
I think you should open separate issues for separate ideas.

**Comment by hwillson** [comment]
I definitely agree with @mitar - would you mind opening separate issues for these ideas, adding a bit more context to each one? Thanks!

**Comment by janat08** [comment]
I was just throwing it out there. The whole value of reactive calls derives from them being hacky.
