### ISSUE TITLE
Dropping Meteor 32-bit support

### ISSUE THREAD

**Issue by hwillson** [meteor/meteor-feature-requests#152]
Given that Mongo is forcing our hand by [discontinuing all 32-bit support](https://docs.mongodb.com/manual/installation/#supported-platforms), the time has come for Meteor to consider dropping its 32-bit support. A few quick notes:

- On MacOS, Meteor currently only supports 64-bit based binaries.
- On Windows, Meteor currently only supports 32-bit based binaries.
- On *nix, Meteor currently supports 32-bit and 64-bit based binaries.

Considering the above, dropping 32-bit support could have the largest impact to Windows and 32-bit only *nix users. Given that only 0.97% of *nix based Meteor (1.4 and 1.5) usage in the last 30 days was on a 32-bit architecture (see https://github.com/meteor/meteor/pull/8864#issuecomment-314963360), the impact to *nix users should be fairly low. It would be great to see similar stats on the Windows side of things, but if Mongo has decided now is a good time to drop 32-bit support, they must have also decided the negative impact of doing so is quite low.

Can anyone think of any compelling reasons why we shouldn't drop 32-bit support? Please keep in mind we're referring to reasons against dropping 32-bit support for Meteor's officially  supported architectures, so not including things like ARM, *BSD, etc.

**Comment by hwillson** [comment]
Hi all - to help move this forward, here is a quick brain dump of changes that will need to be considered as part of this work. This list is not exhaustive, and some of it can only be handled by MDG, but it's a start. Feedback welcome!

## Building / Publishing

- Stop building / publishing `os.linux.x86_32` / `os.windows.x86_32` versions of the following (and start building / publishing `os.windows.x86_64`):
    - Main Meteor distribution (aka the [bootstrap tarball](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/admin/launch-meteor#L73))
    - `dev_bundle`
- Remove the x86_32 options from [`scripts/admin/publish-meteor-tool-on-all-platforms.sh`](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/admin/publish-meteor-tool-on-all-platforms.sh#L45) and [`scripts/admin/publish-meteor-tool-on-arch.sh`](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/admin/publish-meteor-tool-on-arch.sh#L20-L37).

- Update the [Windows installer](https://github.com/meteor/meteor/tree/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/windows/installer) to look for `meteor-bootstrap-os.windows.x86_64.tar.gz` instead of `meteor-bootstrap-os.windows.x86_32.tar.gz`.

- Disable the `os.linux.x86_32` and `os.windows.x86_32` build options available via build.meteor.com (and add `os.windows.x86_64` if the build farm is sticking around).

- Update the architecture checks in the following files, to disallow 32 bit architectures:
    - [`meteor`](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/meteor#L13-L29)
    - [`scripts/admin/launch-meteor`](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/admin/launch-meteor#L47-L68)
    - [`scripts/build-dev-bundle-common.sh`](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/build-dev-bundle-common.sh#L12-L50)

- Disable the [32-bit Mongo version fetch](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/scripts/generate-dev-bundle.ps1#L149-L157) when generating the Window `dev_bundle`.

## CLI

- Remove the [`meteor admin get-machine` 32-bit options](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/tools/cli/commands-packages.js#L476-L477) (`os.linux.x86_32`, `os.windows.x86_32`) and possibly add a `os.windows.x86_64` option (if the build farm is sticking around).

- Adjust the CLI's [allowed architectures](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/tools/cli/commands.js#L34-L39).

- Adjust the [host architecture strings](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/tools/cli/dev-bundle.js#L190-L205) used by the CLI.

- Update all allowed architectures in the [CLI help](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/tools/cli/help.txt) (removing `os.linux.x86_32` and `os.windows.x86_32`, adding `os.windows.x86_64`).

## Utils

- Update all [architecture helper](https://github.com/meteor/meteor/blob/0d8b4dc67a8dc0532db24eb8566c14e964b6ace3/tools/utils/archinfo.js) functions to reflect the goodbye `os.linux.x86_32` /  `os.windows.x86_32`, hello `os.windows.x86_64` changes.

**Comment by aadamsx** [comment]
> On MacOS, Meteor currently only supports 64-bit based binaries.
On Windows, Meteor currently only supports 32-bit based binaries.
On *nix, Meteor currently supports 32-bit and 64-bit based binaries.

Does this mean MacOS and *nix Meteor installs can support Mongo 3.6 today (and it's the Windows build that's holding things up)?

**Comment by davidworkman9** [comment]
@aadamsx There isn't even a development version of 3.6 yet, at least as far as I can tell. So technically MongoDB's holding things up as well.. 😄

**Comment by aadamsx** [comment]
@davidworkman9 -- snarky ain'tcha. I was using the term `holding up` loosely.  :joy:

**Comment by justbill2020** [comment]
Can we get windows 64 bit pushed out sooner rather than later and then remove the 32 bit at a future date... specifically this is an issue as stated in #8871

**Comment by hwillson** [comment]
@justbill2020 Meteor 1.6 now ships with Windows 64-bit support.

**Comment by justbill2020** [comment]
@hwillson This is awesome!!! thank you

**Comment by benjamn** [comment]
@hwillson Do we still need/want to drop 32bit support?

**Comment by justbill2020** [comment]
I still had to copy the 64 bit version of z7.exe to speed up the build times on the latest version... so that hasn’t been updated yet

**Comment by abernix** [comment]
@justbill2020 We added the code that was supposed to make that differentiation to the 64-bit dev bundle, as seen here:

https://github.com/meteor/meteor/blob/9b056f5e911513fb3df716bd524d504cceb863f4/scripts/generate-dev-bundle.ps1#L64-L80

Can you share the full path to the location that you're copying the `7z.exe` to?  Did you reinstall with the new Chocolatey installer? (If not, you're probably not using the 64-bit version of Meteor either.)

**Comment by justbill2020** [comment]
what's a new chocolatey installer? These are projects that I upgrade using the cli. 

This is the path i'm i copy the 64 bit version of 7z.exe: 
```
C:\Users\<USERNAME>\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\bin
```

**Comment by benjamn** [comment]
@justbill2020 Please refer to the Windows installation instructions in the Meteor 1.6 release announcement! https://blog.meteor.com/announcing-meteor-1-6-abf30f29e2c6

**Comment by hwillson** [comment]
@benjamn 

> Do we still need/want to drop 32bit support (any time soon)? Could this wait until Meteor 1.7, perhaps? Or would it simplify things in the short term?

Now that we're allowing 64-bit OS users to use Mongo >= 3.4, I think the pressure to drop 32-bit support has definitely been lessened. I still think it's something that should be done at some point (especially since it will simplify Meteor's codebase and deployment procedures), but waiting until Meteor 1.7 sounds good to me. Thanks!

**Comment by SimonSimCity** [comment]
Isn't this closed by merging https://github.com/meteor/meteor/pull/10933?

**Comment by filipenevola** [comment]
Implemented here https://github.com/meteor/meteor/pull/10933
