### ISSUE TITLE
Update to new faye-websocket/websocket-driver with new http parser

### ISSUE THREAD

**Issue by sdarnell** [meteor/meteor-feature-requests#160]
As per https://github.com/meteor/meteor/issues/8648 I discovered a problem with the websocket-driver package used by faye-websocket. It was causing an assert in debug builds of node, and there is a chance that it also results in some form of memory corruption on refresh - though it is hard to say for certain.

The websocket-driver code has been updated to use a new http parser and avoid using node internals. So this feature request is a placeholder to make sure it gets updated when the faye-websocket/websocket-driver gets released.

See https://github.com/faye/websocket-driver-node/issues/21  

I have manually dropped in replacements and it seems to work in meteor, but I'm unable to reproduce the crashes that others are seeing so I can't be certain whether it fixes https://github.com/meteor/meteor/issues/8648

**Comment by sdarnell** [comment]
For reference, the current (old) versions are:
faye-websocket: 0.11.1  https://www.npmjs.com/package/faye-websocket
websocket-driver: 0.6.5  https://www.npmjs.com/package/websocket-driver

**Comment by hwillson** [comment]
Thanks @sdarnell - I've marked this as `pull-requests-encouraged`. If anyone is interested in working on this, please wait until after the changes from https://github.com/faye/websocket-driver-node/issues/21 have been published and made available via a new `faye-websocket` release.

**Comment by abernix** [comment]
Closing this as the PR has been merged.  This will land in Meteor 1.5.2 and beyond.  Thanks very much, @sdarnell!
