### ISSUE TITLE
Allow override of boilerplate package

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor-feature-requests#169]
I ran into major issues with the standard Meteor boilerplate twice. One was that the Cross Site Policy was missing something. Now I have the problem that since iOS 11 the viewport has to be extended with `viewport-fit=cover` if you want to have your app cover the whole screen estate. See also: https://github.com/meteor/meteor/issues/9041

This would not be any problem if it was possible to override these settings, e.g. by defining them in your own `<head>` template. But this is overruled by the code in the boilerplate.

So I tried to exchange the standard boilerplate-generator package with my custom package. But this doesn't work either. For some magical reason, this package seems to be always reset itself to the standard package.

It would be fantastic if this behaviour could be changed so one has full control over all elements in the `<head>` of your app.

**Comment by mitar** [comment]
Duplicate of #47?

**Comment by derwaldgeist** [comment]
Yep, seems so.

**Comment by mitar** [comment]
But it might be useful to list examples of packages to be overridden there. To motivate the use.
