### ISSUE TITLE
Add an ETag header

### ISSUE THREAD

**Issue by radekmie** [meteor/meteor-feature-requests#176]
What do you think about serving an [ETag header](https://en.wikipedia.org/wiki/HTTP_ETag)? It's not a big deal, but it can reduce the server load a bit, because browser can cache responses. It's kind of more important now, as Meteor have a cleaner way to SSR.

It'll probably be fairly easy: just use [`etag`](https://github.com/jshttp/etag) (express is using it) in the [`webapp/webapp_server.js`](https://github.com/meteor/meteor/blob/devel/packages/webapp/webapp_server.js#L794-L796), right before `res.end()`.

**Comment by hwillson** [comment]
This should already be supported for static files @radekmie - see https://github.com/meteor/meteor/blob/0d7ce023e0902094305960fd5d1268e21702a9f3/packages/webapp/webapp_server.js#L458. Is something not working properly?

**Comment by hwillson** [comment]
Unless you mean generate and set an etag for every response (so not just static files). That isn't currently supported, and might be nice to add.

**Comment by radekmie** [comment]
Yes, I know that. I meant every response. At least the HTML.

**Comment by radekmie** [comment]
It’s already possible. Great!
