### ISSUE TITLE
Meteor & Subresource Integrity

### ISSUE THREAD

**Issue by msavin** [meteor/meteor-feature-requests#180]
This [link](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) explains it all:

> Subresource Integrity (SRI) is a security feature that enables browsers to verify that files they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched file must match.

```javascript
<script src="https://example.com/example-framework.js"
        integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
        crossorigin="anonymous"></script>
```

It would be cool to see this built into the framework.

**Comment by abernix** [comment]
Duplicate of https://github.com/meteor/meteor-feature-requests/issues/35.  Please search first before opening new issues!

**Comment by msavin** [comment]
I tried but must have missed it - thanks for mentioning!
