### ISSUE TITLE
Update to Cordova 7.1.0, Android 6.3.0, and iOS 4.5.3 

### ISSUE THREAD

**Issue by skirunman** [meteor/meteor-feature-requests#196]
This is a minor update to [Cordova 7.1.0](https://cordova.apache.org/news/2017/10/10/tools-release.html) and [Cordova Android 6.3.0](https://cordova.apache.org/announcements/2017/09/27/android-release.html) and any other related plugins. We recently updated to Cordova iOS 4.5.1  https://github.com/meteor/meteor/pull/9137 so ideally for the upcoming Meteor 1.6 release we would have latest Cordova versions included.

**Comment by abernix** [comment]
Meteor 1.6 is already in release candidate status, so unless it's fixing critical or must-fix bugs present in Meteor 1.6, I think this will need to wait.

**Comment by christocracy** [comment]
`cordova@7.1 / android-6.3.0` allows plugin developers (like myself) to *finally* provide a mechanism to solve gradle conflicts with other libraries requesting different versions of `play-services` dependencies.

ie: Plugin developers can now expose `<variable />`s in one's `config.xml` to provide desired version.
```xml
  <preference name="GOOGLE_API_VERSION" default="11.0.1" />
  <framework src="com.google.android.gms:play-services-location:$GOOGLE_API_VERSION"/>
```

```
$ cordova plugin add some-plugin --variable GOOGLE_API_VERSION=11.4.2
$ cordova plugin add phonegap-plugin-push --variable FCM_VERSION=11.4.2
```

**Comment by skirunman** [comment]
Added update to latest[ Cordova iOS 4.5.3](https://cordova.apache.org/announcements/2017/10/31/ios-release.html).
