### ISSUE TITLE
meteor/server-render - Set response status?

### ISSUE THREAD

**Issue by bmanturner** [meteor/meteor-feature-requests#210]
I'm using ```react-router``` + ```redux``` with ```meteor/server-render``` (and it works great) but I think it could be better if it allowed for setting the response status (from 200 to 404/302/301) to accommodate not founds and redirects. I know there is ```WebApp.connectHandlers```, but I don't see a way to use it in conjunction with ```onPageLoad``` since the routes are matched in onPageLoad but the only way I know of to change the response status is via ```WebApp.connectHandlers```.

Thanks.

**Comment by bensventures** [comment]
Seems to have been fixed in the referenced merge above. Here is a crude example on how you can do 404s and 301s inside the `onPageLoad`, hope this helps.

```javascript
import { Meteor } from 'meteor/meteor';
import React from 'react';
import { renderToString } from 'react-dom/server';
import { onPageLoad } from 'meteor/server-render';
import { Random } from 'meteor/random';

import App from '../imports/ui/App.js';
import Page404 from '../imports/pages/p404/p404';

onPageLoad(sink => {
  const url = sink.request.url.pathname;

  // Redirect if accessing the homepage
  if (url === '/') {
    sink.setStatusCode(301);
    sink.redirect(`/id/${Random.id()}/edit`);
  } else if (url.indexOf('id') === -1) { // render a 404 if no id specified and not on homepage
    sink.setStatusCode(404);
    sink.renderIntoElementById(
      'render-target', 
      renderToString(
        <Page404 />
      )
    );
  } else { // Render requested pages
    sink.renderIntoElementById(
      'render-target', 
      renderToString(
        <App route={url} />
      )
    );
  }
});
```
