### ISSUE TITLE
Allow Absolute Imports Without Leading "/"

### ISSUE THREAD

**Issue by stolinski** [meteor/meteor-feature-requests#215]
Having a "/" for absolute imports is different from how it's typically done in Webpack & is causing issues in text editors like VSCode. 

Works with Meteor but not VSCode:

    import { getProduct } from '/imports/api/products/methods';

Works with VSCode but not Meteor:

    import { getProduct } from 'imports/api/products/methods';

**Comment by klaussner** [comment]
I haven't tried it but I think you can do that with [`babel-plugin-module-resolver`](https://github.com/tleunen/babel-plugin-module-resolver).

**Comment by stolinski** [comment]
Can confirm that this works. Thanks!

**Comment by stolinski** [comment]
I should note though that this breaks with dynamic imports.
