### ISSUE TITLE
performance issue with collections observe

### ISSUE THREAD

**Issue by zeroonedev** [meteor/meteor-feature-requests#223]
Migrated from: meteor/meteor#3804

**Comment by theodorDiaconu** [comment]
@zeroonedev have you tried: https://github.com/cult-of-coders/redis-oplog ?

**Comment by zeroonedev** [comment]
Hi @theodorDiaconu thanks for the link, i have heard of redis oplog but haven't tried it yet. The issue i'm having is I need to observe over 100K of documents for changes for an elastic search integration which is chewing up ram and causing issues when i have to restart the app as meteor has to loop over every document in the collection to hold it in memory. Would redis oplog solve these issues?

**Comment by mitar** [comment]
@zeroonedev I would also like this type of observe, where you do not really care about old documents and diff so there would be no need to really consume RAM, you just want an abstraction on top of oplog to sync to another database. This is also a motivation behind #88.

**Comment by KoenLav** [comment]
@klaussner this can be closed in favor of the issue mentioned by @mitar?
