### ISSUE TITLE
Update to Cordova iOS 4.5.4

### ISSUE THREAD

**Issue by bad** [meteor/meteor-feature-requests#240]
Since Cordova-ios was upgraded to 4.5.3 already in meteor/meteor#9213, meteor/meteor-feature-requests#196 could you please update it to 4.5.4.  It has yet more launch storyboard fixes for iPhone X.
It would be nice if this could make it into Meteor 1.6.1.

[Cordova Blog for iOS 4.5.4](https://cordova.apache.org/announcements/2017/11/21/ios-release.html)

**Comment by hwillson** [comment]
Hi @bad - see https://github.com/meteor/meteor/pull/9448. It's coming in Meteor 1.6.1. Thanks!

**Comment by bad** [comment]
On Thu, Dec 21, 2017 at 07:49:15PM +0000, Hugh Willson wrote:
> Hi @bad - see https://github.com/meteor/meteor/pull/9448. It's coming
> in Meteor 1.6.1. Thanks!

Oh. I missed #9448.  Good to see it is coming in 1.6.1.

--chris
