### ISSUE TITLE
Clean client side minimongo?

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor-feature-requests#242]
assume we have "page a" and "page b", both them want to subscribe a publish with same or not same publication name.

```
page a
Meteor.subscribe('a')

pageb
Meteor.subscribe('b')
```

they will use same collection, let's call that collection Test

```
page a
Meteor.subscribe('a')
if ready
data = Test.find().fetch()

pageb
Meteor.subscribe('b')
if ready
data = Test.find().fetch()
```

you can see here we can't specify find selector, because its server only.

```
Meteor.publish 'a' ->
  Test.find { type: 'a' }

Meteor.publish 'b' ->
  Test.find { type: 'b' }
```

so when we switch from page a to page b, it 'sub' page b first, then unsub 'page a'.
the ddp will add docs to Test first, then remove docs from page a.

the Page b will have data from  Page A , especially we use cache page like
https://github.com/ccorcos/meteor-subs-cache
https://github.com/kadirahq/subs-manager

i have make an example

```
git clone https://github.com/crapthings/stop-tracker-and-subscribe-doesn-t-do-anything
cd stop-tracker-and-subscribe-doesn-t-do-anything
meteor npm i
meteor
```

i try this with both react-komposer and react-meteor-data, they all have same issue.

what i do expecting is

when leave page a, stop page a tracker(subscription?), clean minimongo data, then subscribe page b without overlapped data.

**Comment by mitar** [comment]
You can use this package to address this issue: https://github.com/peerlibrary/meteor-subscription-scope

(Disclaimer: I am its author.)

**Comment by crapthings** [comment]
is it possible to solve this with other package ? or  tracker api something ?

**Comment by crapthings** [comment]
@mitar always have solution in his warehouse !!!  i will try ~~~  love love

**Comment by crapthings** [comment]
@mitar 

this package is convenient when meteor publish return "cursor"?
what about some publish is handled by this.added?
will it work too ?

**Comment by mitar** [comment]
Yes.

**Comment by crapthings** [comment]
i close this because minimongo can be cleaned after subscription stop.
because "container(react-komposer, meteor-react-data)"  implement that has order matter, so its cause race problem.
