### ISSUE TITLE
NO_PROXY env is not respected

### ISSUE THREAD

**Issue by AmShaegar13** [meteor/meteor-feature-requests#247]
I am using Rocket.Chat which heavily relies on meteor. Rocket.Chat *needs* internet access which can only be achieved with a proxy from our company network. I am using HTTP_PROXY and HTTPS_PROXY environment variables to use it. Because of that, Rocket.Chat instances cannot connect to each other because the proxy cannot resolve localhost correctly, of course.

This results in a broken Rocket.Chat setup where file uploads, OTR, video calls and much more is not working or not working correctly.

Usually, software respecting those envs also respects NO_PROXY. It contains a comma-separated list of domain suffixes to which the proxy should NOT be applied. Usually, you want to include something like `localhost,127.0.0.1`. In a company network you may have additional domains reserved for internal servers only like `*.local.lan` which ends up in `no_proxy=localhost,127.0.0.1,.local.lan`.

Please respect the NO_PROXY environment variable to distinguish between proxied and non-proxied connections.

**Comment by georg94** [comment]
+1 For this
Are there any news, this would be a important fix to use Meteor in bigger enterprise infrastrucures

**Comment by jh1995** [comment]
+1. Needed too, to avoid NAT-ting the server towards Internet and exclude internal websocket connections (that are not supported by the proxy).

**Comment by AmShaegar13** [comment]
Related #314

**Comment by mathieubremond** [comment]
+1

**Comment by AmShaegar13** [comment]
Should be fixed by https://github.com/meteor/meteor/pull/10914
