### ISSUE TITLE
Control over Reactivity

### ISSUE THREAD

**Issue by formspoint** [meteor/meteor-feature-requests#25]
Simply put, I like to have some level of control over Meteor's reactivity.  Ideally I'd like to be able to specify exactly what data Meteor should react to -- and IMO everything else should not be reactive.

**Comment by mjmasn** [comment]
Isn't this just the difference between using a method and using a subscription? With a method you get the data once, with a subscription you get new data if the cursor changes.

Are you able to give a concrete-ish example of what you're trying to achieve?

**Comment by mitar** [comment]
What do you mean? Can you elaborate please? You can already do that using `Tracker.nonreactive`, for example.

**Comment by StorytellerCZ** [comment]
Since we haven't had elaboration on this I'm closing this issue due to age. Feel free to elaborate and we can re-open it.

**Comment by CaptainN** [comment]
There is now a way to do this with useTracker, and withTracker. It'll take an optional comparator argument which you can use to achieve this functionality.
