### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor-feature-requests#251]
I'm currently getting an error like this:

```
W20180115-19:08:07.779(-8)? (STDERR) packages/modules.js:474
W20180115-19:08:07.889(-8)? (STDERR) export default
W20180115-19:08:07.895(-8)? (STDERR) ^^^^^^
W20180115-19:08:07.896(-8)? (STDERR)
W20180115-19:08:07.922(-8)? (STDERR) SyntaxError: Unexpected token export
W20180115-19:08:07.925(-8)? (STDERR)     at /home/trusktr/Downloads/src/trusktr+chat-widget/.meteor/local/build/programs/server/boot.js:392:18
W20180115-19:08:07.926(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20180115-19:08:07.926(-8)? (STDERR)     at Function._.each._.forEach (/home/trusktr/.meteor/packages/meteor-tool/.1.6.0_1.9z22r.piy41v++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20180115-19:08:07.926(-8)? (STDERR)     at /home/trusktr/Downloads/src/trusktr+chat-widget/.meteor/local/build/programs/server/boot.js:220:5
W20180115-19:08:07.927(-8)? (STDERR)     at /home/trusktr/Downloads/src/trusktr+chat-widget/.meteor/local/build/programs/server/boot.js:463:5
W20180115-19:08:07.930(-8)? (STDERR)     at Function.run (/home/trusktr/Downloads/src/trusktr+chat-widget/.meteor/local/build/programs/server/profile.js:510:12)
W20180115-19:08:07.942(-8)? (STDERR)     at /home/trusktr/Downloads/src/trusktr+chat-widget/.meteor/local/build/programs/server/boot.js:462:11
```

which is obviously not helpful at all.

The problem is because a file in `node_modules` was embedded into `.meteor/local/build/programs/server/packages/modules.js` and has ES6+ syntax.

It'd be great for the error to give the line in the file where the syntax error was (in my case, `node_modules/@awaitbox/meteor-startup/src/index.js`).

**Comment by trusktr** [comment]
Here's a reproduction with the error: https://github.com/trusktr/trusktr.io/tree/meteor-feature-requests-251

Make sure you're on that branch. Then usual steps:

```
npm i
meteor
```

Maybe I'm missing something, but even so, the error could be a lot better.

**Comment by trusktr** [comment]
Aha! It's because a file in `node_modules`, which was embedded into `.meteor/local/build/programs/server/packages/modules.js`, has ES6+ syntax.

If that error gave the whole file path (`./.meteor/local/build/programs/server/packages/modules.js`) I would've found it sooner. Or better yet, if it gave the actual problematic file (`node_modules/@awaitbox/meteor-startup/src/index.js`) it would've been completely helpful.

**Comment by trusktr** [comment]
An example of an error on the client-side that doesn't say which file the error was in:

```
Uncaught (in promise) Error: Cannot find module '../../ui/pages/not-found/not-found.js'
    at makeMissingError (modules-runtime.js?hash=5e485d3e2a49d2506f7ca0df72fcd6a3216a83a5:241)
    at require (modules-runtime.js?hash=5e485d3e2a49d2506f7ca0df72fcd6a3216a83a5:251)
    at eval (routes.js:1)
    at dynamic-import.js?hash=33b7f8d7008f8714463508e13e750eb725b3cd47:139
    at fileEvaluate (modules-runtime.js?hash=5e485d3e2a49d2506f7ca0df72fcd6a3216a83a5:353)
    at Module.require (modules-runtime.js?hash=5e485d3e2a49d2506f7ca0df72fcd6a3216a83a5:248)
    at getNamespace (dynamic-import.js?hash=33b7f8d7008f8714463508e13e750eb725b3cd47:171)
    at dynamic-import.js?hash=33b7f8d7008f8714463508e13e750eb725b3cd47:41
    at meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:1167
    at <anonymous>
```

Of course I can search for `"../../ui/pages/not-found/not-found.js"` and then I can find the file, but that's not ideal.

**Comment by KoenLav** [comment]
@trusktr has this been resolved with the latest Meteor versions?

If so, could you close this issue?
