### ISSUE TITLE
1.6.1 Launch storyboard images

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor-feature-requests#255]
Hi,

would there be any interest to catch launch storyboard images in 1.6.1?

With a single splash for IOS

`<splash src="res/screen/ios/Default@2x~universal~anyany.png" />`

or multiple for IOS 

`<splash src="res/screen/ios/Default@2x~universal~anyany.png" />`
`<splash src="res/screen/ios/Default@2x~universal~comany.png" />`
`<splash src="res/screen/ios/Default@2x~universal~comcom.png" />`
`<splash src="res/screen/ios/Default@3x~universal~anyany.png" />`
`<splash src="res/screen/ios/Default@3x~universal~anycom.png" />`
`<splash src="res/screen/ios/Default@3x~universal~comany.png" />`

https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/

I could indeed push some changes to meteor/tools/cordova/builder.js and wherever else needed.

Tx,
Paul

**Comment by skirunman** [comment]
Hi @paulincai. Trying to understand what you are requesting here. It is possible to already used iOS launch storyboard images in Meteor with the right configuration set in your `mobile-config.js` file as documented in the [Meteor Guide](https://guide.meteor.com/mobile.html#configuring-app-icons-and-launch-screens). In fact, for Cordova launch screens to work correctly on iPhone X you need to use launch storyboards as per [Cordova v4.5.1](https://cordova.apache.org/announcements/2017/09/25/ios-release.html). We are doing this with our Cordova iOS app just fine.

**Comment by paulincai** [comment]
Hi @skirunman, my understanding might be entirely wrong...

The images we use as screen-ratio iamges are considered **"Legacy launch images"** and a "pain for developers". This is the only kind I used so far in the past 2-3 years.

I also understand from Cordova link above, that we can use "Launch storyboard images". 
"the image should be large enough to fit on an iPad Pro 12.9": 2732x2732". This would be a square image to be used with a tag like `<splash src="res/screen/ios/Default@2x~universal~anyany.png" />`. One single image to serve all device sizes as an "anyany" image.

I thought our present Cordova setup in meteor doesn't support that. To be frank with you I am a bit confused now. Please close this if you consider it is unnecessary.

**Comment by skirunman** [comment]
@paulincai With Meteor 1.6 your can either use the legacy launch images OR you can use the Launch storyboard images. The path to the launch storyboard images has to be set correctly. See https://forums.meteor.com/t/deploying-on-iphone-x/40622/5 for more info. I think you can close this.
