### ISSUE TITLE
allow override default user publish fields without autopublish package

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor-feature-requests#260]
i want to add some other fields that comes with the default account publish null in a package, but addAutopublishFields only works with autopublish enabled.

https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L31

https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L740

write this in package will cause tacker rerun two times

```js
Meteor.publish(null, function () {
  if (!this.userId)
    return

  return Meteor.users.find({ _id: this.userId }, { fields: { [CROSS_ACCOUNTS_FIELD]: true } })
})
```

![image](https://user-images.githubusercontent.com/1147704/35600388-96d6673c-0668-11e8-9b8d-04e1b5900c8a.png)

![image](https://user-images.githubusercontent.com/1147704/35600499-2933714c-0669-11e8-9895-b5f02779f32b.png)

**Comment by crapthings** [comment]
can we just allow this without adding autopublish package ?

```js
Accounts.addAutopublishFields({
  forLoggedInUser: [otherFields],
})
```

**Comment by StorytellerCZ** [comment]
@crapthings correct me if I'm wrong, but I think this feature has been implemented:
```
Accounts.addAutopublishFields({
  forLoggedInUser: ['createdAt', 'secret'],
  forOtherUsers: ['createdAt'],
})
```

**Comment by crapthings** [comment]
```js
Accounts.onCreateUser(({ password, ...option }, user) => ({ ...option, ...user }))

Accounts.addAutopublishFields({
  forLoggedInUser: ['hello'],
  forOtherUsers: ['hello'],
})

Meteor.publish('currentUser', function () {
  return Meteor.users.find({ _id: this.userId }, { fields: { services: false } })
})

Meteor.startup(function () {
  if (Meteor.users.findOne()) return
  Accounts.createUser({ username: 'demo', password: 'demo', hello: 'kitty' })
})
```

![image](https://user-images.githubusercontent.com/1147704/120614945-5a08f700-c48a-11eb-878c-205608ec745e.png)

still doesn't work

**Comment by StorytellerCZ** [comment]
Check the `defaultFieldSelector` option of [Accounts.config](https://docs.meteor.com/api/accounts-multi.html#AccountsCommon-config)

**Comment by crapthings** [comment]
it looks the defaultFieldSelector doesn't override by config

```js
Accounts.config({
  defaultFieldSelector: { hello: 1 }
})
```

```js
Accounts.config({
  defaultFieldSelector: { fields: { hello: 1 } }
})
```

```js
Accounts.config({
  defaultFieldSelector: { projection: { hello: 1 } }
})
```

![image](https://user-images.githubusercontent.com/1147704/120736465-dd742800-c51e-11eb-9a95-b9ef9b6c76b3.png)
