### ISSUE TITLE
Adding Packages from Git Repo

### ISSUE THREAD

**Issue by MastaBaba** [meteor/meteor-feature-requests#263]
Migrated from: meteor/meteor#2919

**Comment by mitar** [comment]
Using `git submodule` to add them to `packages` directory seems to work pretty well?

**Comment by MastaBaba** [comment]
Thanks. Have you got a link to a walkthrough on how to accomplish this?

**Comment by dr-dimitru** [comment]
@MastaBaba perhaps answer could be found at [this thread](https://github.com/meteor/guide/issues/682#issue-279220790).

**Comment by MastaBaba** [comment]
Thanks @dr-dimitru. I'm not sure I fully follow, though. Based on your link, is it enough to just edit my package.json to something like:

```
{
  "name": "my app",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.39",
    "babel-runtime": "^6.20.0",
    "meteor-node-stubs": "~0.2.4",
    "my-inserted-package-from-git": "https://github.com/somepackagelinkhere"
  }
}
```

**Comment by dr-dimitru** [comment]
@MastaBaba right.
 1. Update `package.json`;
 2. Install: `meteor npm install`

**Comment by MastaBaba** [comment]
Thanks. The practical problem I had and the solution I used is described here:

https://stackoverflow.com/a/48609213/1374538

**Comment by KoenLav** [comment]
@MastaBaba I guess this can be closed?
