### ISSUE TITLE
Proper support for using Accounts on a different connection

### ISSUE THREAD

**Issue by vuhrmeister** [meteor/meteor-feature-requests#264]
There may be situations where you need a different App for authentication. Let's consider the following scenario.

## The scenario
Let's assume we have two different user groups: A and B, being end customers and retailers. Both are working on the same data and communicating with each other, but having the need for a completely different app interface. Therefore you don't want to have one large code basis since you don't want to deliver unnecessary code to the client (besides of maintainability reasons).

For simplicity we have 3 apps (might be more in a more complex scenario):
App 1: WebApp (or Cordova) for user group A
App 2: WebApp (or Cordova) for user group B 
App 3: The backend (including user management / authentication)

App 1 & 2 should be pretty dump, so they should be just the frontend. They should still point to their origin server for hot code push. But for authentication there must be only one user management. Therefore both frontend apps should reliably use the backend connection for authentication.

## The current situation
If you search for that topic you will find a lot of forum posts trying to get this working, some of them written in 2015 and before. So obviously there is a demand on that.

In [this issue](https://github.com/meteor/meteor/issues/8357) I already explained my opinion about it and @hwillson encouraged me to write this feature request.

So by today there is no clean way of getting things working. The most discussed solution looks similar to
```javascript
const connection = DDP.connect('http://localhost:4010')
Accounts.connection = connection
Meteor.users = new Meteor.Collection('users', { connection })
```

At first glance this works. You can register and log in. But as you reload the browser you're logged out again. Then people do something like

```javascript
Tracker.autorun(function () {
  const token = Session.get('_storedLoginToken')
  if (token) {
    Meteor.loginWithToken(token, (err) => {
      // …
    })
  }
})

Tracker.autorun(function () {
  if (Meteor.user()) {
    // using u2622:persistent-session
    Session.setPersistent('_storedLoginToken', Accounts._storedLoginToken())
  }
})
```

The point here is that `Accounts` get [initialized right away](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/client_main.js#L9) when the `accounts-base` package is loaded. Then `_initLocalStorage()` is called before you have the chance to set the `Account`'s connection. Therefore [here](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/localstorage_token.js#L101) it still uses the `Meteor.connection` and doesn't look for the connection we set manually. 

Then there is documentation about [AccountsClient](https://docs.meteor.com/api/accounts-multi.html#AccountsClient). But this is only useful if I'm fine having the default `Accounts` instance as well. There are [plenty](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_common.js#L272) of [functions](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_client.js#L189) on it which references the default `Accounts` in any case. So with the solution discussed above you are in a total mess.

## A better solution

There is an undocumented (and deprecated) way to get this done in just one line of code. I myself make use of this in my project.

```javascript
__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = Meteor.settings.backendUrl
```

With just this single line of code everything works (for me) as expected (well, almost, will discuss that later). `Accounts` get initialized right away with the proper connection so there is no orphan connection out there. All methods like `Meteor#userId()` or `Meteor#loggingIn` are using the proper connection.

So I plead for making this a public API. It might be configurable via settings file or ENV var. 

Maybe I'm to naive that this is all you need to do. Might be that I didn't overlook the whole picture. So any feedback is welcome. And hopefully we will find a solution which can be implemented.

### Connection instances
Configuring a connection url for `Accounts` might be fine, but I struggled with the fact that when calling a method or subscribing to a publication, I was not known as a logged in user. I found out, that I set up two connections to the backend (one implicitly via Accounts initialization and one for use in my app). My workaround is to always use the `Accounts.connection`.    
I don't really like that. So maybe a cleaner way would be to set up a connection and provide that instance to `Accounts` (I know, that would be much more work to achieve that).

### OAuth
Actually I realized, that for the accounts system as a whole there are more issues to consider. While authentication with password is pretty straight forward, OAuth is not. The problem comes with redirects from the provider. Authentication is done in a popup which then communicates with the `opener` to finalize the login process. Because of cross-origin policy this does not work anymore if you redirect to your authentication server which runs on a different host as the frontend app.    
For now I need to start my app with the same database connection as for the backend. Now my frontend app receive the response from the OAuth provider and stores the information in the `meteor_oauth_pendingCredentials` collection and the backend app can access those information and actually finalize the process.   
The goal should be, of course, not to work around over the database.

**Comment by filipenevola** [comment]
Let's centralize this on #372
