### ISSUE TITLE
Update to Cordova 8.0, Cordova Android 7.0 and newest plugins

### ISSUE THREAD

**Issue by skirunman** [meteor/meteor-feature-requests#265]
There are yet again some key Cordova features and bug fixes in the latest [versions](https://github.com/apache/cordova-plugin-statusbar/commits/master) including fixes for iPhone X and latest Android build tools. 

We are continuing to play catch up with Cordova releases so it would sure be nice if we could decouple Cordova releases from Meteor releases as per this [feature request](https://github.com/meteor/meteor-feature-requests/issues/112). Barring someone taking up that more ambitious effort (@hwillson ?) then we need to at least update to these latest major versions. I am a bit concerned with the [changes](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html) in `cordova-android-7.0` as they look to be breaking changes that might effect our build tools in a more significant way.

**Comment by hwillson** [comment]
Some Cordova 8 investigative work has been completed, and it looks like it might be a bit too early to think about Cordova 8 integration (there appears to be a few kinks that need to be worked out on the Cordova side). If anyone is interested in looking into this further, that sounds great! Otherwise, there might not be much progress on this until the Cordova 8.x release has matured a bit.

**Comment by theavijitsarkar** [comment]
Any update on this? Also, is it possible to de-couple meteor and cordova?

**Comment by paulincai** [comment]
@hwillson any chance this is going into 1.7.1?!  cordova-ios is now at 4.5.5 (Meteor 1.7.0.5 is on 4.5.4)  and cordova-android at 7.1.1 (Meteor 1.7.0.5 is at 6.4.0).

Cordova-android below 7.1.0 prevents the use of the Push plugin at version 2.2.0 which contains an update of FCM and some fixes related to one unique push message: [v2.2.0](https://github.com/phonegap/phonegap-plugin-push/blob/master/CHANGELOG.md#v220-2017-10-23)

**Comment by 2gen** [comment]
@paulincai Were you able to find a way to update cordova-android to version 7.1.0? I'd also like to update the phonegap push plugin to version 2.2.0.

**Comment by paulincai** [comment]
@2gen  :(. I am fully dependent on what Meteor has to offer. Any issues you have with Push? I have it working decently but never tried above Android 6.x.

**Comment by 2gen** [comment]
Can't get it to work with the .on('notification') event if the app is in the background. No matter the notification payload used, and if there is the content-available attribute set or not. If the app is in foreground it works correctly.

**Comment by paulincai** [comment]
@2gen is this the only listener that doesn't work out of more of them or you haven't set other listeners. I mean ... you know this is related to the Cordova version as in ... it worked fine in another version / context. Did you go through this one: https://github.com/raix/push/issues/325 ?

**Comment by FishSaidNo** [comment]
> @hwillson any chance this is going into 1.7.1?! cordova-ios is now at 4.5.5 (Meteor 1.7.0.5 is on 4.5.4) and cordova-android at 7.1.1 (Meteor 1.7.0.5 is at 6.4.0).
> 
> Cordova-android below 7.1.0 prevents the use of the Push plugin at version 2.2.0 which contains an update of FCM and some fixes related to one unique push message: [v2.2.0](https://github.com/phonegap/phonegap-plugin-push/blob/master/CHANGELOG.md#v220-2017-10-23)

+1 For this. 
We are currently limited to using version 2.1.3 of cordova-plugin-push (released Feb 2). There have been numerous bug-fixes and enhancements since then.

**Comment by eskan** [comment]
+1
Many plugins fixes need newest version

**Comment by brunoneumann** [comment]
Interessed on how to decouple Cordova from Meteor. I'm needing Cordova 8.

**Comment by KoenLav** [comment]
@benjamn is there still anything specific holding Meteor back in terms of Cordova version?

Now Cordova 9 has been released it might good to take a look bumping the version.

**Comment by yorrd** [comment]
please do, there are incompatibilities because of this coming up, preventing us from using certain plugins

**Comment by skirunman** [comment]
This has been done in https://github.com/meteor/meteor/pull/10810 so closing.
