### ISSUE TITLE
Allow overriding Facebook API version in facebook-oauth

### ISSUE THREAD

**Issue by juho** [meteor/meteor-feature-requests#273]
`facebook-oauth` should allow user-definable API version for the FB API calls. Currently the default version for new apps is v2.12 and in the packages it's hardcoded at v2.8, and the package has to play catch-up.

**Comment by StorytellerCZ** [comment]
https://github.com/meteor/meteor/pull/11362
You can now override the default API version by setting `Meteor.settings.public.packages.facebook-oauth.apiVersion`, but we usually keep pretty up to date with the latest Facebook API, so there should be no need.
