### ISSUE TITLE
[cordova] include resource-file

### ISSUE THREAD

**Issue by eskan** [meteor/meteor-feature-requests#279]
Hi ,
add a way to include resource files from **mobile-config.js** that will be converted in cordova config.xml like this

```
<platform name="android">
  <resource-file src="google-services.json" target="app/google-services.json" />
</platform>
```
or
```
<platform name="ios">
  <resource-file src="GoogleService-Info.plist" />
</platform>
```
Cordova documentation :
http://cordova.apache.org/docs/en/7.x/config_ref/index.html#resource-file

Those files are needed by cordova plugins that use Google Service like **phonegap-plugin-push** via cocoaPods.

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md
Regards,

**Comment by eskan** [comment]
Hi,
this is a proposal, in mobile-config.js 
`
App.addResourceFile(src,target,[platform]);
`
the src is relative to meteor/project folder. The meteor builder will copy this file in the cordova project root and fill config.xml with
`<resource-file src=src.file target=target/>
`
then cordova will copy file to target.
If it's fine, i'll submit a PR.
Regards,

**Comment by eskan** [comment]
Should be added in 1.7 release

**Comment by Nauzer** [comment]
is it correct this didn't make it in 1.7? Any idea when it would be added?

**Comment by chrishanyu** [comment]
I'm using 1.8.1-rc.1 and this is added. Couldn't find any documentation on it though.

**Comment by dovydaskukalis** [comment]
Anyone managed to make it work when the source file is inside a folder? I always get `Source path does not exist` no matter what I try like `folder/file.png`, `./folder/file.png`.

**Comment by brucejo75** [comment]
This pretty much only works if the resource file is in the root of your project.

This [code](https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js#L393-L416) looks like the culprit:
```javascript
  configureAndCopyResourceFiles(resourceFiles, iosElement, androidElement) {
    _.each(resourceFiles, resourceFile => {
      // Copy file in cordova project root directory
      var filename = path.parse(resourceFile.src).base;
      files.copyFile(
        files.pathResolve(this.projectContext.projectDir, resourceFile.src),
        files.pathJoin(this.projectRoot, filename));
      // And entry in config.xml
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "android")) {
        androidElement.element('resource-file', {
          src: resourceFile.src,
          target: resourceFile.target
        });
      }
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "ios")) {
        iosElement.element('resource-file', {
          src: resourceFile.src,
          target: resourceFile.target
        });
      }
    });
  }
```

Essentially, the code copies from it's source location
```javascript
files.pathResolve(this.projectContext.projectDir, resourceFile.src)
```
then places it at the root of the cordova build:
```javascript
files.pathJoin(this.projectRoot, filename))
```
Which is fine, but then it creates a `resource-file` directive that is looking for the resource file relative to the root of the build tree:
```javascript
        androidElement.element('resource-file', {
          src: resourceFile.src,
          target: resourceFile.target
        });
```
So if you place your resources at the root of the meteor project tree all will work.  To make it work with resources in folders either:
1. Need to make the files copy to a path relative to the cordova build root.
2. Change the `resource-file` directive to grab the file from the root.

Either way there is the potential for collision, but I think I like # 1.

Also, I like the idea of documenting it.  Because this is an awesome feature!

Hey, @eskan, any chance you could address?

**Comment by brucejo75** [comment]
Also @eskan, this [code](https://github.com/meteor/meteor/blob/devel/tools/cordova/builder.js#L401-L402):
```javascript
      if (!resourceFile.platform ||
          (resourceFile.platform && resourceFile.platform === "android")) {
```

Does not process the platform code as spec'ed.
- does not handle 'both'
- does not handle an array of platforms (standard meteor platform spec)

**Comment by eskan** [comment]
@brucejo75 you should fill an issue at least for your last post and may be a feature request or an issue to add the ability to put file in other directory than root.

**Comment by brucejo75** [comment]
@eska, OK, will do.  But the issue is not a feature request.  As spec'ed the source of the file from the meteor project can be relative.  That does not work.
