### ISSUE TITLE
Automatically open tab in default browser when app has started

### ISSUE THREAD

**Issue by yorrd** [meteor/meteor-feature-requests#289]
So that you don't have to type localhost:port yourself. I saw the feature at a friends who uses some react start script

**Comment by hexsprite** [comment]
This could easily be a community package. You would just need to register a `Meteor.startup()` hook that opens the tab.

**Comment by StorytellerCZ** [comment]
I agree with @hexsprite, not to mentions that opening a new tab/browser window might not be always desired (server only apps, cordova, etc.).
