### ISSUE TITLE
Add Auth Cookie to Accounts-Base for SSR 

### ISSUE THREAD

**Issue by toinevk** [meteor/meteor-feature-requests#295]
**A description of the problem you're trying to solve, including *why* you think this is a problem**

Currently, Meteor sets tokens in local storage, in addition I understand that DDP also exposes the userId to all methods. However, when using Meteor with Apollo https://github.com/apollographql/meteor-integration/issues/116, user information is currently not available for SSR Applications who rely on Meteor's authentication solution. 

Some other relevant information that should be considered: https://blog.meteor.com/why-meteor-doesnt-use-session-cookies-e988544f52c9

**An overview of the suggested solution**

Set Cookie with user information. At a minimum the cookie should be [secure and httpOnly](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies) (potentially samesite - but this does not have extensive support yet).

**Comment by CaptainN** [comment]
I'd be willing to look into implementing this if there is interest in incorporating it in core.

**Comment by CaptainN** [comment]
Could a service worker be used to circumvent the issues surrounding cookies? I would think a Service Worker could be used to read the auth token from LocalStorage, then pass that to the server in whatever request instead of using a cookie. What do you think?

**Comment by filipenevola** [comment]
Let's centralize this on #372
