### ISSUE TITLE
Official VUE.js support

### ISSUE THREAD

**Issue by boustanihani** [meteor/meteor-feature-requests#300]
Please add official VUE.js support.

Thanks :)

**Comment by imcoddy** [comment]
Would love to see this as well

**Comment by StorytellerCZ** [comment]
@boustanihani @imcoddy Any specifics to what you mean by "official support"? There are packages that make Vue work and there is official tutorial as well.

**Comment by filipenevola** [comment]
Hi, make sure you check our official Vue Tutorial https://vue-tutorial.meteor.com/
