### ISSUE TITLE
Command Line Flag to start with mainModule

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor-feature-requests#302]
Now that #135 has been implemented with `meteor.mainModule` in `package.json`, it would be great to have a command line flag (`--with-main-module`) to be used when creating a Meteor project. This would allow you to easily get started with a project that doesn't have eagerly loaded files.

**Comment by benjamn** [comment]
Are you trying to create a Meteor project from an existing Node project directory? The default `meteor create` and `meteor create --minimal` apps come with `meteor.mainModule` and `meteor.testModule` out of the box, now.

**Comment by merlinpatt** [comment]
Ah, I think I ran `create` after 1.7 was released but before I had upgraded my Meteor version. I'll close this since it's already in there
