### ISSUE TITLE
Move Meteor Feature Requests Over to Canny.io to Leverage Voting

### ISSUE THREAD

**Issue by acomito** [meteor/meteor-feature-requests#306]
This could help with quantifying and organizing feature demands even more.

**Comment by imkarthikk** [comment]
Nice suggestion. But isn't Canny.io paid? And also on the expensive side? Instead, hellonext (https://hellonext.co) is free for open source projects. Simpler than Canny in many ways.

**Comment by filipenevola** [comment]
I agree.

I believe we are going to propose something with Votes and a better system to classify priority and demand in the next months for Meteor.

**Comment by imkarthikk** [comment]
> I agree.
> 
> I believe we are going to propose something with Votes and a better system to classify priority and demand in the next months for Meteor.

Beautiful. Please feel free to ping me here. Meteor can use [Hellonext](https://hellonext.co/) for free. A way for me to give back to the community.

**Comment by mitar** [comment]
GitHub has votes?
