### ISSUE TITLE
Bring "native" typescript support

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor-feature-requests#307]
It's clear right now that TypeScript is a standard. And if we want to keep Meteor on the bleeding edge we should have built-in and treat typescript as a first class citizen.

**Comment by benjamn** [comment]
Already tracking this! #285 😉

**Comment by theodorDiaconu** [comment]
@benjamn to be frank with you ... if we have `mainModule` wouldn't it be just adding the `tsc watcher` to dump in a index file that `mainModule` loads ? And we have like fully native support ? (This just hit me)

**Comment by smeijer** [comment]
So what you're saying is;

1) declare meteor `imports` in a `meteor.d.ts`, so `tsm` "understands" (ignores) those.
2) let `tsm` compile to a `stage1.bundle.js`
3) let `meteor` `import` `stage1.bundle.js` by setting it's `mainModule: stage1.bundle.js`
4) let `meteor` compile `bundle.js`, whereby it resolves missing `meteor/x:y` imports.

Or do you plan having a mirrored directory, where every source file has a by `tsm` transpiled version?

1) declare meteor `imports` in a `meteor.d.ts`, so `tsm` "understands" those.
2) let `tsm` compile `src/${file}.ts` to `.compiled/${file}.js`
3) set mainModule to `src/main.js`, which imports an entry file from `../.compiled`

**Comment by theodorDiaconu** [comment]
I think that what I would do is to have a sort of folder which is `.gitignored`. 

Have a pre-start script that runs the compilation first time before the code runs, and also run in parallel a `tsc watch`

I would use `mainModule` so bye bye eager loading. I would keep my code in src/{server}/{client}/**/*.ts. And Have it exported to dist/client/index.js | dist/server/index.js .

Dist is the one ignored.
