### ISSUE TITLE
Mongo 4.0 - multi-document ACID transactions

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor-feature-requests#315]
Mongo 4.0 includes multi-document ACID transactions. 
https://www.mongodb.com/transactions

**Description of the Problem**  
Explaining to people who don't understand the CAP theorem that there are other considerations when designing databases.  Explaining that convergence-to-consistency is usually satisfactory for most non-financial applications.  Having countless SQL vs NoSQL arguments.  Potential double-spend bugs in financial applications without ACID support.   etc. etc.  

**Overview of the Suggest Solution**  
Upgrade to Mongo 4.0.

Apparently ACID compliance is enabled on a per-collection basis.  We might need to include some sort of collection initialization option, similar to `idGeneration` or `_ensureIndex()`.

**Comment by mitar** [comment]
It would be interesting to see how this interacts with oplog. ;-)

**Comment by klaussner** [comment]
@awatson1978 I've already opened two feature requests (#269, #311) and a PR (meteor/meteor#10058) for that. 🙂
