### ISSUE TITLE
Update Nodemailer

### ISSUE THREAD

**Issue by cunneen** [meteor/meteor-feature-requests#317]
The core email package has a dependency on node4mailer, a fork of an old version of nodemailer.

Meteor no longer runs on node 4, and the new nodemailer has some nifty features, particularly https://ethereal.email/ .

This is great for development and testing, where the email can be viewed and tested with a variety of clients (unlike the status quo with meteor, where a message is logged to the console if the MAIL_URL environment variable isn't set).

So I propose:

1. Updating the core email package to use nodemailer instead of node4mailer, and 
2. update the core email package's [devModeSend](https://github.com/meteor/meteor/blob/e91b3776e54ca9e1607bf89e0cebd32170eb2c1d/packages/email/email.js#L78) method to use ethereal.email .

**Comment by StorytellerCZ** [comment]
Agree with point 1. Though for point 2 that is something that I think should be left behind a flag or some other selectable option that by default is false as turning it on by default would break backward compatibility and there are other tools for that functionality as well. So maybe an additional package that if you install it will support this functionality on dev, which would allow for other similar tools to easily plugin.
Still we can do point 1 without needing to address point 2, so I think we should proceed on that.

**Comment by StorytellerCZ** [comment]
@cunneen There is @msavin [Meteor Toys](http://meteor.toys/) that can catch e-mails.

**Comment by StorytellerCZ** [comment]
Since in dev mode the email is shown in console I think that is fine and satisfies the idea behind point 2. Closing.
