### ISSUE TITLE
Create a 'meteor.js' bundle, possibly on cdn, to share cache.

### ISSUE THREAD

**Issue by smeijer** [meteor/meteor-feature-requests#332]
So, the basic idea; we now have bundle splitting / dynamic loading available in Meteor.

What I'm already doing, is using a dynamic import as soon as possible (router level), to show a loading screen and load the rest of the application.

Wouldn't it be possible to have the base bundle be a 'meteor only' bundle, that loads our application bundle? This base-bundle only needs to change when Meteor (or its packages) changes / has been updated.

The application bundle would change on every app update.

This is already possible if I only think about my own application. I'm more curious if it would be possible (and profitable) to have an `mdg-hosted` `meteor bundle`, that we can all use. That way, every Meteor application on the internet, could use the exact same bundle (per version), and speed up the initial loading dramatically.

**Comment by smeijer** [comment]
Stretching this one a bit. It might even be possible to get a base docker image; where Meteor is installed with this `base bundle` precompiled. 

And that the end user could have a layer with only his code (+ `node_modules`) compiled.

Yes, it might lead to a slightly larger base image, but I think that outweighs the benefits.

Am I missing something here; or would this be quite possible?

**Comment by avalanche1** [comment]
https://github.com/meteor/meteor-feature-requests/issues/277

**Comment by smeijer** [comment]
Great minds think alike. 😁, closing this one in favor of #277.
