### ISSUE TITLE
Avoid rebuilding the app three times on error

### ISSUE THREAD

**Issue by vblagomir** [meteor/meteor-feature-requests#335]
**Description**
Since Meteor tries to restart the app three times when there is a development server runtime error, it takes longer time to read error logs, since they are published 3 times.

**Suggestion**
Make the count of restarts as an option or environment variable.

**Details**
This has been requested firstly in meteor/meteor#6481, but was closed and suggested to create a feature request.

**Comment by benjamn** [comment]
I like this idea, and I would even go further: instead of allowing the restart count to be configured, let's get rid of the multiple restart feature altogether. In more than four years working on Meteor, I have never once seen the second or third restart actually fix any problems.

**Comment by vblagomir** [comment]
Great that you like it! I have not seen the second or third restart actually fix any problem, but _maybe_ someone had.. :-)

**Comment by benjamn** [comment]
If you (or anyone) is interested in attempting a pull request, [here's the relevant code](https://github.com/meteor/meteor/blob/18762f97a285f05f868442a09a806699049e885b/tools/runners/run-app.js#L961-L964). Of course you could just change that `3` to a `1`, but ideally we could clean up any lingering multiple restart logic too.

**Comment by StorytellerCZ** [comment]
This has been implemented in Meteor 1.9
