### ISSUE TITLE
Allow formatting of server logging output

### ISSUE THREAD

**Issue by slowdownitsfine** [meteor/meteor-feature-requests#337]
I admit this is a very picky feature request 😅.

When the meteor server process prints messages while being executed, it will prepend these with something like this `I20181104-17:55:25.844(0)?`

Personally when developing locally, this much information seems unnecessary. Additionally on narrower, low res screens or when using a tabbed terminal window with server process and shell side by side this might lead to undesirable line breaks.

Therefore I would like to have a way of altering / customizing the prepended [metaPrefix](https://github.com/meteor/meteor/blob/devel/packages/logging/logging.js#L293) string.

I have not found a way of overriding this at runtime but would also be very happy with such a solution.

Thank you.

**Comment by StorytellerCZ** [comment]
If you found a solution, wouldn't a section in a guide about this suffice or is it needlessly difficult?

**Comment by dcusan** [comment]
Unfortunately I have not found a solution yet, that's why I posted this.

**Comment by StorytellerCZ** [comment]
Sorry, misread initially. I though we had something in one of my projects, but I was mistaken.

**Comment by smeijer** [comment]
We can disable that timestamp with `meteor --raw-logs`. By using `--raw-logs` I'm able to have a colorful output in development, while I write pure JSON in production.

![image](https://user-images.githubusercontent.com/1196524/95753445-eb302100-0ca1-11eb-9a2d-191fb29b0e83.png)
