### ISSUE TITLE
Please move <script> tags out of the <body> tag

### ISSUE THREAD

**Issue by msavin** [meteor/meteor-feature-requests#341]
I believe it is incorrect in terms of semantics, and it makes inspecting the <body> tag a lot more difficult.

**Comment by klaussner** [comment]
`script` elements are allowed in the `body` (the [`body` element](https://html.spec.whatwg.org/multipage/sections.html#the-body-element) allows "flow content" as children, [which includes `script` elements](https://html.spec.whatwg.org/multipage/dom.html#flow-content-2)). Placing `script` elements at the end of the `body` is useful to avoid blocking the HTML parser, which has to wait until the browser finishes downloading and executing the scripts that it encounters in the HTML.

Maybe we could move all `script` tags to the `head` and add the `defer` attribute but I'm not sure if that's a backwards compatible change or if/how it affect page load performance.

**Comment by dr-dimitru** [comment]
Hey @msavin @klaussner ,

 - Looks like this is what we all want: https://github.com/meteor/meteor-feature-requests/issues/267
 - This is what was done for CSS: https://github.com/meteor/meteor-feature-requests/issues/24

```html
<meteor-bundled-css />
```

**Comment by klaussner** [comment]
Thanks, @dr-dimitru! Closing in favor of meteor/meteor-feature-requests#267.
