### ISSUE TITLE
Update Meteor to Node.js 10

### ISSUE THREAD

**Issue by vlasky** [meteor/meteor-feature-requests#342]
In [the official Meteor 1.6 announcement dated 1st November 2017](https://blog.meteor.com/announcing-meteor-1-6-abf30f29e2c6), it was stated that:

> Meteor will likely update directly to Node.js 10 as soon as it reaches LTS status in October 2018.

Well, [Node.js 10.13.0 became the LTS version on 2018-10-30](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.13.0).

As of today, the current Node.js LTS version is 10.15.

Would appreciate an update from the MDG as to when an official Meteor update to Node.js 10 is likely to happen.

**Comment by KoenLav** [comment]
I guess this can be closed: https://github.com/meteor/meteor/pull/10527

**Comment by antoinep92** [comment]
For those still wondering, 1.8.2 was just released with node 8.16.2 and apparently 1.9 (currently in beta) will jump to 12.13.1, skipping node 10 altogether since 12 is now LTS. [Source](https://github.com/meteor/meteor/blob/release-1.9/scripts/build-dev-bundle-common.sh)

**Comment by filipenevola** [comment]
Yes, Meteor 1.9 is going to use Node 12.

**Comment by mitar** [comment]
Shouldn't this be closed once Meteor 1.9 is released?

**Comment by filipenevola** [comment]
We are not going to update to Node.js 10 then I don't see any reason to keep this opened.
