### ISSUE TITLE
Subresource Integrity (SRI) support

### ISSUE THREAD

**Issue by mitar** [meteor/meteor-feature-requests#35]
Migrated from: meteor/meteor#8286

**Comment by macsj200** [comment]
What would this take to create? I'd be happy to collaborate on something like this.

**Comment by mitar** [comment]
Just an extra attribute on everything rendered in the base HTML output of Meteor, I would say. And I think extending manifest file to contain sha256 or some other hash needed for SRI.

**Comment by macsj200** [comment]
Obviously that PR could use some work. Do you have any feedback?

**Comment by msavin** [comment]
For those unfamiliar, this [link](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) explains it all:

> Subresource Integrity (SRI) is a security feature that enables browsers to verify that files they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched file must match.

```javascript
<script src="https://example.com/example-framework.js"
        integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
        crossorigin="anonymous"></script>
```

**Comment by mitar** [comment]
Just to be sure, why is this needed in Meteor? So in general you trust the server from which you are getting content. And Meteor by default serves JavaScript and CSS from there.

If you have any custom things in the HTML referencing outside resources, then you can manually add hashing attributes to it. So what is the use case here exactly? That a Meteor bundle is served by a CDN? How is this configured? By whom?

**Comment by mitar** [comment]
This is now supported by doing on the server:

```js
import {WebAppInternals} from 'meteor/webapp';

WebAppInternals.enableSubresourceIntegrity();
```

**Comment by ivan133** [comment]
I'm sorry but how to make it work?
If I enable it on the server I got on the client:

Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4000/packages/modules.js?hash=ee555d54b1c4510f4ca238bef50d03621987c250' with computed SHA-256 integrity '3IwV08+W6iydsTYn0SI2TGUzvuoJ9z0VsuEqg6qUz38='. The resource has been blocked.

Should I do something on client-side?
Maybe it won't work for development mode?

**Comment by mitar** [comment]
It should just work. But I have seen such issues for one non-core package. I do not know why. So if you can make a small reproduction repository that would be great. And open an issue as a bug report in the Meteor repository.

**Comment by msavin** [comment]
Why not make it on by default?

**Comment by mitar** [comment]
I think people might worry about development loading time (it takes time to compute hash during hot reloading), but I do not know why would one have SRI enabled during development anyway.

Otherwise, I agree. Some things like this and CSP should just be by default on. (With an option to remove a package/setting to disable it.) But it is really best practices these days. I will open few feature requests for this.

**Comment by msavin** [comment]
Yah it’s definitely a production only feature
