### ISSUE TITLE
Update Cordova from version 7 to 9

### ISSUE THREAD

**Issue by dhrubins** [meteor/meteor-feature-requests#362]
Now that Cordova 9 has been released for almost 6 months, is there interest in upgrading since we're now two major versions out of date?

**Comment by nguyenhaduchieu** [comment]
Any update?

**Comment by filipenevola** [comment]
Yes @nguyenhaduchieu , this is in progress.

If you are willing to help please comment in the umbrella PR https://github.com/meteor/meteor/pull/10810.

More information here.
https://github.com/meteor/meteor/blob/devel/Roadmap.md#update-cordova-to-9

**Comment by hexsprite** [comment]
This can be closed.

**Comment by afrokick** [comment]
@filipenevola ping
