### ISSUE TITLE
Allow the oauth server package to parse post body data

### ISSUE THREAD

**Issue by jramer** [meteor/meteor-feature-requests#370]
The current middleware for the oauth server is only able to receive query params, not post body data. 
This makes it unable to properly parse a scope request from "Sign in with Apple", apples oauth service.
Sign in with Apple is required for apps that include other oauth services and this will make it important to support it in cordova apps.

I have built a working [apple oauth package](https://atmospherejs.com/bigowl/apple-oauth) but it needs this change to work seamlessly.

(ahem. my package isn't tested on cordova yet, only web... 😬)

**Comment by mitar** [comment]
See also: https://github.com/meteor/meteor/issues/10491

**Comment by mitar** [comment]
It seems PR is already out there: https://github.com/meteor/meteor/pull/10501

**Comment by jramer** [comment]
Oh, sorry. I have only seen the pull req. and not the issue. Been working on my own pull request and started to read you guidelines for making one.
My PR (to be) builds on meteor/meteor#10501 and I have passing tests but with console errors that I need some help with.
See: https://github.com/jramer/meteor/tree/feature/oauth-post-body
