### ISSUE TITLE
Accessing settings in mobile-config.js

### ISSUE THREAD

**Issue by Testato** [meteor/meteor-feature-requests#38]
### Before opening a new feature request, please note:

- Issues in this repository are reserved for feature requests only. Bugs should be reported in the main [Meteor repo issue tracker](https://github.com/meteor/meteor).
- Check to see if a similar feature request already exists or has been closed before.

### Feature requests should include as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

See [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#feature-requests) for more detail on what is expected of a feature request.

**Comment by skirunman** [comment]
FYI, this was implemented in https://github.com/meteor/meteor/pull/9873
