### ISSUE TITLE
Update Meteor to Node.js 14

### ISSUE THREAD

**Issue by fpreti** [meteor/meteor-feature-requests#402]
Hi,
are you planning to migrate to node 14? [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/) 
Active LTS Start 2020-10-20

thanks,
Francesco

**Comment by filipenevola** [comment]
Sure, we always want to be up-to-date with Node.js

**Comment by StorytellerCZ** [comment]
I think this is something that can be tackled during Hacktoberfest. From what I have seen there are two main issues to address for the update:
* internationalization - changed from minimal to everything (I have already seen where this is set on the Meteor's side when building Node, I just need to find it again and change that)
* modules support - this might shorten build time for server, but I have no idea what to do here

**Comment by Kampflaus** [comment]
Hi there,

what is the current status of Node.js 14 in Meteor?

**Comment by filipenevola** [comment]
We already have a branch with Node.js 14 but we are prioritizing first Meteor 2.0 with HMR and Tree-shaking + Meteor cloud with free deploy with MongoDB on Galaxy 😉

**Comment by Kampflaus** [comment]
Thanks for your feedback!

We bundle with [nexe](https://github.com/nexe/nexe/releases) so we need to switch to Node.js 14 soon because unfortunately the build system from Nexe [isn't working](https://github.com/nexe/nexe/issues/754) with >12.18.2. The new target will be 14.x.

**Comment by filipenevola** [comment]
@Kampflaus we had a problem with Windows build but I don't think it's related to Node.js 14 specifically.

Do you use Meteor on Windows? It would be good to have someone testing Meteor + Node.js 14 even before we fix this issue on Windows build.

Let me know if you would be interested in running your app with Meteor beta and Node.js 14.

**Comment by Kampflaus** [comment]
@filipenevola Yes, our app runs on Windows and Linux. We could try out the beta.

**Comment by filipenevola** [comment]
We have the Windows build already working.

But a few tests are still failing on CI (not on my machine) https://github.com/meteor/meteor/pull/11197

We are probably going to have a beta version including Node 14 on Meteor 2.1 soon.

**Comment by damienfa** [comment]
Any news about Meteor for NodeJs 14?

**Comment by filipenevola** [comment]
Yes, all the testing are passing on my machine, we are investigating at this moment why they are failing on CircleCI.

See the current status in the PR description https://github.com/meteor/meteor/pull/11197

I'm also doing some tests in this branch `circle-ci-error-node-14`, to try to identify why CircleCI is failing.

**Comment by Kampflaus** [comment]
> 
> 
> Thanks for your feedback!
> 
> We bundle with [nexe](https://github.com/nexe/nexe/releases) so we need to switch to Node.js 14 soon because unfortunately the build system from Nexe [isn't working](https://github.com/nexe/nexe/issues/754) with >12.18.2. The new target will be 14.x.

Good news thanks to the latest Meteor release. Node version 12.21.0 seems to fix the existing problems since 12.18.2. We could successfully build our app with Meteor 2.1 and Nexe.

Nevertheless we are looking forward to Node 14. Thanks for your efforts.

**Comment by StorytellerCZ** [comment]
Meteor 2.3 is now in beta, so I'm closing this issue.
