### ISSUE TITLE
Allow more collection update operations

### ISSUE THREAD

**Issue by frankyjuang** [meteor/meteor-feature-requests#403]
Right now only a handful of update operations are allowed (https://github.com/meteor/meteor/blob/5b0f004e6c57f0cf8c1313646790cfb42b7065fa/packages/allow-deny/allow-deny.js#L369).
More useful operations have been added to mongodb, e.g. `$currentDate`, `$max`, `$min` (https://docs.mongodb.com/manual/reference/operator/update/#id1).
Shall we allow more operations?

**Comment by StorytellerCZ** [comment]
Yes, I would love to see that.

**Comment by StorytellerCZ** [comment]
By the way `$min` and `$max` operators are already supported.

**Comment by StorytellerCZ** [comment]
So after an inspection everything except `$mul` is already supported in some way. I'm adding `$mul` now.

**Comment by StorytellerCZ** [comment]
@frankyjuang With `$mul` now in Meteor v2.2 I think this feature is done. Feel free to re-open if something is missing.
