### ISSUE TITLE
Tool: Implement packages list tree to json output using meteor list --json flag

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor-feature-requests#406]
Currently I am writing a GitHub action, that resolves the current packages tree that results [from the `meteor list --tree` command](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L1134)  and checks for outdated package versions.
However, this involves manually parsing the `|--` symbols from the output to re-create the structure as a data model.

It would be much easier (and less error-prone) for this (and potential other actions / ci) to generate the packages tree directly as json file.
From what I perceive,there would be the following changes

- add a `json` flag to the [options](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L1140)
- implement a variable [output target symbol](https://github.com/meteor/meteor/blob/devel/tools/cli/commands-packages.js#L1196) that uses json syntax elements, if the `--json` flag is active.
- Otherwise, if `--json` is omitted, keep the actual output symbols for `--tree`
- If `--tree` is not active, `--json` is irgnored

I would myself start a PR,if this would get a green light

**Comment by filipenevola** [comment]
@jankapunkt 🟢

**Comment by jankapunkt** [comment]
PR opened at https://github.com/meteor/meteor/pull/11165

**Comment by filipenevola** [comment]
Merged. It will be available on Meteor 1.12
