### ISSUE TITLE
Manage environment variables from Galaxy Platform

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor-feature-requests#422]
### Problem
if you forgot to set an environment variable in your application, you will have to deploy again and wait for it.

### Solution
I have used Heroku to deploy my meteor apps, and something that I liked is that I was able to modify environment variables from Heroku platform. I could add, remove or update variables. So, this feature will be great to add to Galaxy platform.

If you are in a pinch, this could be very helpful.

**Comment by diavrank** [comment]
I have just seen the feature in versions tab. So, this is already considered in Galaxy.

**Comment by filipenevola** [comment]
Yes, you can always edit your current settings in the Versions tab at the current version 😉
