### ISSUE TITLE
Support .meteorignore files to restrict which files can be compiled or imported by Meteor apps or packages

### ISSUE THREAD

**Issue by ejfrancis** [meteor/meteor-feature-requests#5]
Migrated from: meteor/meteor#6002
(open since Jan 14, 2016)

The syntax should be the same as .gitignore or .npmignore files.

**Comment by krismeister** [comment]
I followed to this request 3 levels deep. Its most certainly has been open since before 2016.

**Comment by antoniopresto** [comment]
I hope this helps: https://github.com/meteor/meteor/pull/9080
