### ISSUE TITLE
Add package aliasing to the build system

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor-feature-requests#56]
In some cases it would be useful to alias one package for another, such as replacing react and react-dom with preact or react-lite. This can be a great way to reduce the bundle size of the app.

Additionally, it may be useful to define a separate replacement on the server, web, cordova, etc. For example, leave React on server builds for SSR, and use preact for web builds.

The feature could follow the webpack convention, which is very simple to set up. In some config file we could list a bit of json to set up the alias:

```
  web: {
    alias: {
      react: 'preact-compat',
      'react-dom': 'preact-compat'
    }
  }
```

**Comment by mitar** [comment]
This might be related to #47.

**Comment by CaptainN** [comment]
#47 (or the older ticket it links to) is making the case for a similar feature for atmosphere packages, which would also be great.

**Comment by benjamn** [comment]
Can we consolidate this into #60, where I recently commented? Sorry I didn't see this issue first.

**Comment by hwillson** [comment]
Sure thing - thanks for posting this @CaptainN; if you don't mind continuing the discussion over in #60, that would be great. Thanks!
