### ISSUE TITLE
Make the Accounts collection name configurable

### ISSUE THREAD

**Issue by Levino** [meteor/meteor-feature-requests#61]
Migrated from: meteor/meteor#4995

Currently the mongo collection for the users is always ```users```. It would be very nice to able to change this default value to something like ```meteor-users``` or whatever. Background might be the case where the Meteor app shares a database with other applications where ```users``` is already taken.

**Comment by mitar** [comment]
That is probably a duplicate of #20? (Or a special case of #20.)

**Comment by Levino** [comment]
Yes looks like it. Closing this here.
