### ISSUE TITLE
`meteor build` should accept a `platforms` option

### ISSUE THREAD

**Issue by dmitry-sher** [meteor/meteor-feature-requests#63]
Migrated from: meteor/meteor#7144

**Comment by theodorDiaconu** [comment]
This is a must.

**Comment by Twisterking** [comment]
Is there an update on this? I need this option!

**Comment by riatzukiza** [comment]
bumping, I agree this should be a feature. My use case is that I usually develop on windows/linux, but I run a vm for mac, and I would like to only compile ios in the vm, doing the android work in a vm when I have it already set up on linux would be slower and a hassle.

**Comment by wreiske** [comment]
I would also like to see this feature. There's so many times I want to just build iOS or just Android, etc., and I have to manually remote-platform, add-platform depending on what I'm focusing on for the day.

**Comment by boredland** [comment]
I was using meteor in ~2016 and was annoyed by this. For tragic reasons I have to build a meteor cordova app again. This issue still exists.

**Comment by StorytellerCZ** [comment]
Will be added in Meteor 2.3
