### ISSUE TITLE
Add a onUpdateUser hook to the accounts-base package

### ISSUE THREAD

**Issue by FGM** [meteor/meteor-feature-requests#68]
Migrated from: meteor/meteor#7213

**Comment by FGM** [comment]
Just had a look at Meteor 1.6 alpha 3 and this mechanism is still absent.

**Comment by zimme** [comment]
@FGM, did you ever look into creating a PR for this? If so, any thoughts on how an implementation would look?

**Comment by mitar** [comment]
I think you could get this by having a global server-side observe on `services` key for the user and then run the update on `profile`.

**Comment by FGM** [comment]
@zimme I didn't because meteor contribution rules mention not to send a PR unless one has been requested by MDG.

@mitar Possibly. At any rate, IMHO since such hooks already exist on login and logout and it's marked with a XXX in the code, it's more about fixing an inconsistency than adding a feature, and it should ideally use the same "hook" mechanism as the other two.

**Comment by hwillson** [comment]
Addressed by PR https://github.com/meteor/meteor/pull/9042 - thanks!
